Разметка index.html
htmlacademy-adaptive/358737-pink-23 pull request #2
Opened 2021-08-03 17:25 UTC by archi174

2021-08-04 22:26 UTC, sealeye requested changes
Хорошая разметка, есть всего одна ошибка.

2021-08-04 22:26 UTC, sealeye commented on source/index.html
> +    <div class="applications applications__wrapper">
У одного и того же тега не может быть класс блока и класс элемента от этого же блока. 
Класс элемента всегда вложен в блок.

2021-08-06 16:47 UTC, archi174 commented on source/index.html
> +    <div class="applications applications__wrapper">
Внес правки согласно замечаниям. 
Получается для каждого блока я создаю свой центровщик в виде элемента block__wrapper, не правильнее ли использовать центровщик как отдельный блок wrapper?? При изменении размера центровщика править придется в одном месте, а так искать центровщики каждого блока...

2021-08-06 17:15 UTC, sealeye commented on source/index.html
> +    <div class="applications applications__wrapper">
Да, можно использовать отдельный класс. 
Но тут есть альтернатива в препроцессорах - миксин. Можно в миксере один раз задать ширину и использовать этот миксин у разных классов.

2021-08-06 17:16 UTC, merged