Разметка form.html photo.html
htmlacademy-adaptive/358737-pink-23 pull request #3
Opened 2021-08-07 20:06 UTC by archi174

2021-08-09 19:18 UTC, sealeye commented on source/form.html
> +  <section class="modal modal-error">
здесь error это модификатор

2021-08-09 19:18 UTC, sealeye commented on source/form.html
> +  <section class="modal modal-success">
и тут success это модификатор

2021-08-09 19:19 UTC, sealeye commented on source/photo.html
> +      <figure class="gallery__item">
Тут каждый пост можно сделать БЭМ блоком, так как его можно переиспользовать на любых страницах.

2021-08-09 19:20 UTC, sealeye commented on source/photo.html
> +                <span class="img-editor-form__item-icon img-editor-form__item-icon--crop"></span>
Тут иконки лучше сделать через тег  button, потому что они кликабельны в мобильной версии.

2021-08-09 19:21 UTC, sealeye requested changes
В целом, с разметкой всё хорошо, нужны маленькие дополнения.

2021-08-10 11:36 UTC, archi174 commented on source/form.html
> +  <section class="modal modal-error">
Исправил на modal--error

2021-08-10 11:37 UTC, archi174 commented on source/form.html
> +  <section class="modal modal-success">
Исправил на modal--success

2021-08-10 11:38 UTC, archi174 commented on source/photo.html
> +      <figure class="gallery__item">
Выделил figure отдельным блоком gallery-item

2021-08-10 11:38 UTC, archi174 commented on source/photo.html
> +                <span class="img-editor-form__item-icon img-editor-form__item-icon--crop"></span>
Исправил на button

2021-08-10 13:49 UTC, merged